Dataset: https://www.kaggle.com/gregorut/videogamesales

In [4]:
import pandas as pd

In [5]:
sales = pd.read_csv("vgsales.csv", index_col = "Rank")

In [6]:
sales

                                                   Name  ... Global_Sales
Rank                                                     ...
1                                            Wii Sports  ...        82.74
2                                     Super Mario Bros.  ...        40.24
3                                        Mario Kart Wii  ...        35.82
4                                     Wii Sports Resort  ...        33.00
5                              Pokemon Red/Pokemon Blue  ...        31.37
...                                                 ...  ...          ...
16596                Woody Woodpecker in Crazy Castle 5  ...         0.01
16597                     Men in Black II: Alien Escape  ...         0.01
16598  SCORE International Baja 1000: The Official Game  ...         0.01
16599                                        Know How 2  ...         0.01
16600                                  Spirits & Spells  ...         0.01

[16598 rows x 10 columns]

In [7]:
sales.dtypes

Name             object
Platform         object
Year            float64
Genre            object
Publisher        object
NA_Sales        float64
EU_Sales        float64
JP_Sales        float64
Other_Sales     float64
Global_Sales    float64
dtype: object

In [8]:
sales.head(5)
sales.head(n = 5)

                          Name Platform  ...  Other_Sales Global_Sales
Rank                                     ...
1                   Wii Sports      Wii  ...         8.46        82.74
2            Super Mario Bros.      NES  ...         0.77        40.24
3               Mario Kart Wii      Wii  ...         3.31        35.82
4            Wii Sports Resort      Wii  ...         2.96        33.00
5     Pokemon Red/Pokemon Blue       GB  ...         1.00        31.37

[5 rows x 10 columns]

In [9]:
sales.tail(20)

                                                    Name  ... Global_Sales
Rank                                                      ...
16581                      Outdoors Unleashed: Africa 3D  ...         0.01
16582                                  PGA European Tour  ...         0.01
16583                                          Real Rode  ...         0.01
16584                                          Fit & Fun  ...         0.01
16585                                    Planet Monsters  ...         0.01
16586                                     Carmageddon 64  ...         0.01
16587                                   Bust-A-Move 3000  ...         0.01
16588                                             Breach  ...         0.01
16589                     Secret Files 2: Puritas Cordis  ...         0.01
16590                           Mezase!! Tsuri Master DS  ...         0.01
16591                                   Mega Brain Boost  ...         0.01
16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...  ...         0.01
16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...  ...         0.01
16594                                Myst IV: Revelation  ...         0.01
16595                                           Plushees  ...         0.01
16596                 Woody Woodpecker in Crazy Castle 5  ...         0.01
16597                      Men in Black II: Alien Escape  ...         0.01
16598   SCORE International Baja 1000: The Official Game  ...         0.01
16599                                         Know How 2  ...         0.01
16600                                   Spirits & Spells  ...         0.01

[20 rows x 10 columns]

In [10]:
sales.sort_values("Name")
sales.sort_values("Name", ascending = True)

                                          Name  ... Global_Sales
Rank                                            ...
4756                               '98 Koshien  ...         0.41
8359                .hack//G.U. Vol.1//Rebirth  ...         0.17
7109              .hack//G.U. Vol.2//Reminisce  ...         0.23
8604   .hack//G.U. Vol.2//Reminisce (jp sales)  ...         0.16
8306             .hack//G.U. Vol.3//Redemption  ...         0.17
...                                        ...  ...          ...
628                               uDraw Studio  ...         2.46
7837              uDraw Studio: Instant Artist  ...         0.19
15526             uDraw Studio: Instant Artist  ...         0.02
471                 wwe Smackdown vs. Raw 2006  ...         3.00
9137              Â¡Shin Chan Flipa en colores!  ...         0.14

[16598 rows x 10 columns]

In [11]:
sales.sort_values("Name", ascending=False)

                                          Name  ... Global_Sales
Rank                                            ...
9137              Â¡Shin Chan Flipa en colores!  ...         0.14
471                 wwe Smackdown vs. Raw 2006  ...         3.00
15526             uDraw Studio: Instant Artist  ...         0.02
7837              uDraw Studio: Instant Artist  ...         0.19
628                               uDraw Studio  ...         2.46
...                                        ...  ...          ...
8306             .hack//G.U. Vol.3//Redemption  ...         0.17
8604   .hack//G.U. Vol.2//Reminisce (jp sales)  ...         0.16
7109              .hack//G.U. Vol.2//Reminisce  ...         0.23
8359                .hack//G.U. Vol.1//Rebirth  ...         0.17
4756                               '98 Koshien  ...         0.41

[16598 rows x 10 columns]

In [12]:
sales.sort_values("Name", ascending=False).head(3)

                               Name Platform  ...  Other_Sales Global_Sales
Rank                                          ...
9137   Â¡Shin Chan Flipa en colores!       DS  ...         0.00         0.14
471      wwe Smackdown vs. Raw 2006      PS2  ...         0.41         3.00
15526  uDraw Studio: Instant Artist     X360  ...         0.00         0.02

[3 rows x 10 columns]

In [13]:
sales.sort_values(["Platform", "Global_Sales"], ascending=False)

                                 Name Platform  ...  Other_Sales Global_Sales
Rank                                            ...
102         Call of Duty: Black Ops 3     XOne  ...         0.67         7.30
194    Call of Duty: Advanced Warfare     XOne  ...         0.38         5.13
198                Grand Theft Auto V     XOne  ...         0.41         5.08
261                 Halo 5: Guardians     XOne  ...         0.39         4.26
288                         Fallout 4     XOne  ...         0.37         4.09
...                               ...      ...  ...          ...          ...
8762                         Home Run     2600  ...         0.00         0.15
9108                            Krull     2600  ...         0.00         0.14
9497            RealSports Volleyball     2600  ...         0.00         0.13
11718                  Super Football     2600  ...         0.00         0.08
11751                  Super Baseball     2600  ...         0.00         0.07

[16598 rows x 10 columns]

In [14]:
sales.sort_values(["Platform", "Global_Sales"], ascending=[True, False])

                           Name Platform  ...  Other_Sales Global_Sales
Rank                                      ...
90                      Pac-Man     2600  ...         0.08         7.81
240                    Pitfall!     2600  ...         0.05         4.50
259                   Asteroids     2600  ...         0.05         4.31
545             Missile Command     2600  ...         0.03         2.76
608              Space Invaders     2600  ...         0.03         2.53
...                         ...      ...  ...          ...          ...
16533  SÃ©bastien Loeb Rally Evo     XOne  ...         0.00         0.01
16534             Hitman (2016)     XOne  ...         0.00         0.01
16565              Mighty No. 9     XOne  ...         0.00         0.01
16572        Resident Evil 4 HD     XOne  ...         0.00         0.01
16579         Rugby Challenge 3     XOne  ...         0.00         0.01

[16598 rows x 10 columns]

In [15]:
# inplace will make the change permanent
sales.sort_values(["Platform", "Global_Sales"], ascending=[True, False], inplace = True)

In [16]:
sales.head()

                 Name Platform    Year  ... JP_Sales Other_Sales  Global_Sales
Rank                                    ...
90            Pac-Man     2600  1982.0  ...      0.0        0.08          7.81
240          Pitfall!     2600  1981.0  ...      0.0        0.05          4.50
259         Asteroids     2600  1980.0  ...      0.0        0.05          4.31
545   Missile Command     2600  1980.0  ...      0.0        0.03          2.76
608    Space Invaders     2600     NaN  ...      0.0        0.03          2.53

[5 rows x 10 columns]

In [17]:
sales.sort_index(ascending = True, inplace = True)

In [18]:
# Optimizations
## Number of entries - non-null count = number of NaN values
sales.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16598 entries, 1 to 16600
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          16598 non-null  object
 1   Platform      16598 non-null  object
 2   Year          16327 non-null  float64
 3   Genre         16598 non-null  object
 4   Publisher     16540 non-null  object
 5   NA_Sales      16598 non-null  float64
 6   EU_Sales      16598 non-null  float64
 7   JP_Sales      16598 non-null  float64
 8   Other_Sales   16598 non-null  float64
 9   Global_Sales  16598 non-null  float64
dtypes: float64(6), object(4)
memory usage: 1.4+ MB

In [19]:
## drops rows with NaN value in the column year
sales.dropna(subset = ["Year"], inplace=True)

In [20]:
# outputs a series
sales["Year"]

Rank
1        2006.0
2        1985.0
3        2008.0
4        2009.0
5        1996.0
          ...
16596    2002.0
16597    2003.0
16598    2008.0
16599    2010.0
16600    2003.0
Name: Year, Length: 16327, dtype: float64

In [21]:
sales["Year"].astype(int)

Rank
1        2006
2        1985
3        2008
4        2009
5        1996
         ...
16596    2002
16597    2003
16598    2008
16599    2010
16600    2003
Name: Year, Length: 16327, dtype: int64

In [22]:
sales["Year"] = sales["Year"].astype(int)

In [23]:
sales["Year"]

Rank
1        2006
2        1985
3        2008
4        2009
5        1996
         ...
16596    2002
16597    2003
16598    2008
16599    2010
16600    2003
Name: Year, Length: 16327, dtype: int64

In [24]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16327 entries, 1 to 16600
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          16327 non-null  object
 1   Platform      16327 non-null  object
 2   Year          16327 non-null  int64
 3   Genre         16327 non-null  object
 4   Publisher     16291 non-null  object
 5   NA_Sales      16327 non-null  float64
 6   EU_Sales      16327 non-null  float64
 7   JP_Sales      16327 non-null  float64
 8   Other_Sales   16327 non-null  float64
 9   Global_Sales  16327 non-null  float64
dtypes: float64(5), int64(1), object(4)
memory usage: 1.4+ MB

In [25]:
sales.nunique()

Name            11360
Platform           31
Year               39
Genre              12
Publisher         576
NA_Sales          408
EU_Sales          305
JP_Sales          244
Other_Sales       157
Global_Sales      621
dtype: int64

In [26]:
sales["Genre"] = sales["Genre"].astype("category")
sales["Platform"] = sales["Platform"].astype("category")
sales.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16327 entries, 1 to 16600
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          16327 non-null  object
 1   Platform      16327 non-null  category
 2   Year          16327 non-null  int64
 3   Genre         16327 non-null  category
 4   Publisher     16291 non-null  object
 5   NA_Sales      16327 non-null  float64
 6   EU_Sales      16327 non-null  float64
 7   JP_Sales      16327 non-null  float64
 8   Other_Sales   16327 non-null  float64
 9   Global_Sales  16327 non-null  float64
dtypes: category(2), float64(5), int64(1), object(2)
memory usage: 1.2+ MB

In [27]:
# Selecting Columns
sales

                                                   Name  ... Global_Sales
Rank                                                     ...
1                                            Wii Sports  ...        82.74
2                                     Super Mario Bros.  ...        40.24
3                                        Mario Kart Wii  ...        35.82
4                                     Wii Sports Resort  ...        33.00
5                              Pokemon Red/Pokemon Blue  ...        31.37
...                                                 ...  ...          ...
16596                Woody Woodpecker in Crazy Castle 5  ...         0.01
16597                     Men in Black II: Alien Escape  ...         0.01
16598  SCORE International Baja 1000: The Official Game  ...         0.01
16599                                        Know How 2  ...         0.01
16600                                  Spirits & Spells  ...         0.01

[16327 rows x 10 columns]

In [28]:
sales["Publisher"]

Rank
1          Nintendo
2          Nintendo
3          Nintendo
4          Nintendo
5          Nintendo
            ...
16596         Kemco
16597    Infogrames
16598    Activision
16599      7G//AMES
16600       Wanadoo
Name: Publisher, Length: 16327, dtype: object

In [29]:
# list in square brackets
sales[["Publisher", "Name", "Platform"]]

        Publisher                                              Name Platform
Rank
1        Nintendo                                        Wii Sports      Wii
2        Nintendo                                 Super Mario Bros.      NES
3        Nintendo                                    Mario Kart Wii      Wii
4        Nintendo                                 Wii Sports Resort      Wii
5        Nintendo                          Pokemon Red/Pokemon Blue       GB
...           ...                                               ...      ...
16596       Kemco                Woody Woodpecker in Crazy Castle 5      GBA
16597  Infogrames                     Men in Black II: Alien Escape       GC
16598  Activision  SCORE International Baja 1000: The Official Game      PS2
16599    7G//AMES                                        Know How 2       DS
16600     Wanadoo                                  Spirits & Spells      GBA

[16327 rows x 3 columns]

In [30]:
sales.head()

                          Name Platform  ...  Other_Sales Global_Sales
Rank                                     ...
1                   Wii Sports      Wii  ...         8.46        82.74
2            Super Mario Bros.      NES  ...         0.77        40.24
3               Mario Kart Wii      Wii  ...         3.31        35.82
4            Wii Sports Resort      Wii  ...         2.96        33.00
5     Pokemon Red/Pokemon Blue       GB  ...         1.00        31.37

[5 rows x 10 columns]

In [31]:
sales.reset_index(inplace = True)

In [32]:
sales.set_index("Name", inplace = True)

In [33]:
sales

                                                   Rank  ... Global_Sales
Name                                                     ...
Wii Sports                                            1  ...        82.74
Super Mario Bros.                                     2  ...        40.24
Mario Kart Wii                                        3  ...        35.82
Wii Sports Resort                                     4  ...        33.00
Pokemon Red/Pokemon Blue                              5  ...        31.37
...                                                 ...  ...          ...
Woody Woodpecker in Crazy Castle 5                16596  ...         0.01
Men in Black II: Alien Escape                     16597  ...         0.01
SCORE International Baja 1000: The Official Game  16598  ...         0.01
Know How 2                                        16599  ...         0.01
Spirits & Spells                                  16600  ...         0.01

[16327 rows x 10 columns]

In [34]:
sales.sort_index(inplace = True)

In [35]:
sales["Genre"].value_counts()

Action          3253
Sports          2304
Misc            1710
Role-Playing    1471
Shooter         1282
Adventure       1276
Racing          1226
Platform         876
Simulation       851
Fighting         836
Strategy         671
Puzzle           571
Name: Genre, dtype: int64

In [36]:
sales["Genre"].value_counts(normalize=True)

Action          0.199241
Sports          0.141116
Misc            0.104734
Role-Playing    0.090096
Shooter         0.078520
Adventure       0.078153
Racing          0.075090
Platform        0.053653
Simulation      0.052122
Fighting        0.051204
Strategy        0.041098
Puzzle          0.034973
Name: Genre, dtype: float64

In [37]:
sales["Genre"].value_counts(normalize=True) * 100

Action          19.924052
Sports          14.111594
Misc            10.473449
Role-Playing     9.009616
Shooter          7.852024
Adventure        7.815275
Racing           7.509034
Platform         5.365346
Simulation       5.212225
Fighting         5.120353
Strategy         4.109757
Puzzle           3.497274
Name: Genre, dtype: float64

In [38]:
# Selecting Rows
sales.head()

                                         Rank  ... Global_Sales
Name                                           ...
'98 Koshien                              4756  ...         0.41
.hack//G.U. Vol.1//Rebirth               8359  ...         0.17
.hack//G.U. Vol.2//Reminisce             7109  ...         0.23
.hack//G.U. Vol.2//Reminisce (jp sales)  8604  ...         0.16
.hack//G.U. Vol.3//Redemption            8306  ...         0.17

[5 rows x 10 columns]

In [39]:
# You can select by name, label or by position
sales.loc["Wii Sports"]

Rank                   1
Platform             Wii
Year                2006
Genre             Sports
Publisher       Nintendo
NA_Sales           41.49
EU_Sales           29.02
JP_Sales            3.77
Other_Sales         8.46
Global_Sales       82.74
Name: Wii Sports, dtype: object

In [40]:
sales.loc["Wii Sports", "Genre"]

'Sports'

In [41]:
sales.loc["Fallout 4"]

           Rank Platform  Year  ... JP_Sales Other_Sales  Global_Sales
Name                            ...
Fallout 4  1632       PC  2015  ...     0.00        0.10          1.23
Fallout 4   110      PS4  2015  ...     0.24        1.10          6.96
Fallout 4   288     XOne  2015  ...     0.01        0.37          4.09

[3 rows x 10 columns]

In [42]:
sales.loc[["Fallout 4", "Grand Theft Auto V"], ["Platform", "Global_Sales"]]

                   Platform  Global_Sales
Name
Fallout 4                PC          1.23
Fallout 4               PS4          6.96
Fallout 4              XOne          4.09
Grand Theft Auto V       PC          1.08
Grand Theft Auto V     XOne          5.08
Grand Theft Auto V      PS3         21.40
Grand Theft Auto V      PS4         11.98
Grand Theft Auto V     X360         16.38

In [43]:
# Filtering
sales.head()

                                         Rank  ... Global_Sales
Name                                           ...
'98 Koshien                              4756  ...         0.41
.hack//G.U. Vol.1//Rebirth               8359  ...         0.17
.hack//G.U. Vol.2//Reminisce             7109  ...         0.23
.hack//G.U. Vol.2//Reminisce (jp sales)  8604  ...         0.16
.hack//G.U. Vol.3//Redemption            8306  ...         0.17

[5 rows x 10 columns]

In [44]:
sales["Publisher"] == "Square Enix"

Name
'98 Koshien                                False
.hack//G.U. Vol.1//Rebirth                 False
.hack//G.U. Vol.2//Reminisce               False
.hack//G.U. Vol.2//Reminisce (jp sales)    False
.hack//G.U. Vol.3//Redemption              False
                                           ...
thinkSMART: Chess for Kids                 False
uDraw Studio                               False
uDraw Studio: Instant Artist               False
uDraw Studio: Instant Artist               False
Â¡Shin Chan Flipa en colores!               False
Name: Publisher, Length: 16327, dtype: bool

In [45]:
sales[sales["Publisher"] == "Square Enix"]

                                          Rank  ... Global_Sales
Name                                            ...
Arkanoid DS                              12430  ...         0.06
Army Corps of Hell                       10456  ...         0.10
Blood of Bahamut                         11003  ...         0.09
Bust-A-Move Universe                      5717  ...         0.31
Chaos Rings III                          12713  ...         0.06
...                                        ...  ...          ...
Tomb Raider (2013)                         895  ...         1.92
Tomb Raider (2013)                        3361  ...         0.60
Valkyrie Profile 2: Silmeria              4177  ...         0.47
Valkyrie Profile: Covenant of the Plume   4574  ...         0.42
Valkyrie Profile: Lenneth                 5182  ...         0.36

[231 rows x 10 columns]

In [46]:
square_enix = sales["Publisher"] == "Square Enix"
sales[square_enix]

                                          Rank  ... Global_Sales
Name                                            ...
Arkanoid DS                              12430  ...         0.06
Army Corps of Hell                       10456  ...         0.10
Blood of Bahamut                         11003  ...         0.09
Bust-A-Move Universe                      5717  ...         0.31
Chaos Rings III                          12713  ...         0.06
...                                        ...  ...          ...
Tomb Raider (2013)                         895  ...         1.92
Tomb Raider (2013)                        3361  ...         0.60
Valkyrie Profile 2: Silmeria              4177  ...         0.47
Valkyrie Profile: Covenant of the Plume   4574  ...         0.42
Valkyrie Profile: Lenneth                 5182  ...         0.36

[231 rows x 10 columns]

In [47]:
action_genre = sales["Genre"] == "Action"
sales[action_genre]

                                    Rank Platform  ...  Other_Sales Global_Sales
Name                                               ...
.hack: Sekai no Mukou ni + Versus  14279      PS3  ...         0.00         0.03
007: Quantum of Solace              1275     X360  ...         0.14         1.49
007: Quantum of Solace              9320       DS  ...         0.01         0.14
007: Quantum of Solace              4501      PS2  ...         0.26         0.43
007: Quantum of Solace              3040      Wii  ...         0.07         0.67
...                                  ...      ...  ...          ...          ...
[Prototype]                         1505     X360  ...         0.12         1.31
[Prototype]                         1604      PS3  ...         0.19         1.24
inFAMOUS                             488      PS3  ...         0.37         2.94
inFAMOUS 2                           941      PS3  ...         0.23         1.85
inFAMOUS: Second Son                 539      PS4  ...         0.47         2.78

[3253 rows x 10 columns]

In [48]:
# AND
sales[square_enix & action_genre]

                                                     Rank  ... Global_Sales
Name                                                       ...
Army Corps of Hell                                  10456  ...         0.10
Dragon Quest Heroes II: Twin Kings and the Prop...   6205  ...         0.28
Dragon Quest Heroes II: Twin Kings and the Prop...   9540  ...         0.13
Dragon Quest Heroes II: Twin Kings and the Prop...   7062  ...         0.23
Dragon Quest Heroes: Rocket Slime                    4397  ...         0.45
Dragon Quest Heroes: The World's Tree Woe and t...   2864  ...         0.71
Dragon Quest Heroes: The World's Tree Woe and t...   4028  ...         0.49
Final Fantasy Crystal Chronicles: The Crystal B...   4820  ...         0.40
Final Fantasy XIV: Heavensward                       9729  ...         0.12
Final Fantasy XIV: Heavensward                      15643  ...         0.02
Final Fantasy XIV: Heavensward                      15271  ...         0.02
Hitman (2016)                                       13649  ...         0.04
Hitman (2016)                                       16534  ...         0.01
Hitman: Absolution                                    747  ...         2.19
Hitman: Absolution                                    999  ...         1.76
Hitman: Absolution                                   6709  ...         0.25
Hitman: HD Trilogy                                   7202  ...         0.22
Hitman: HD Trilogy                                   8055  ...         0.18
Just Cause 2                                          978  ...         1.78
Just Cause 2                                         1134  ...         1.62
Just Cause 2                                         9549  ...         0.13
Just Cause 3                                         2369  ...         0.88
Just Cause 3                                          949  ...         1.83
Just Cause 3                                         9138  ...         0.14
Kingdom Hearts 3D: Dream Drop Distance               1178  ...         1.58
Kuroshitsuji: Phantom & Ghost                       14061  ...         0.04
Lara Croft and the Temple of Osiris                 11267  ...         0.08
Lara Croft and the Temple of Osiris                 15642  ...         0.02
Murdered: Soul Suspect                               8574  ...         0.16
Murdered: Soul Suspect                               8767  ...         0.15
Murdered: Soul Suspect                              12690  ...         0.06
Murdered: Soul Suspect                               5615  ...         0.32
Murdered: Soul Suspect                              10308  ...         0.11
Nanashi no Game Me                                  14578  ...         0.03
Sleeping Dogs                                        9678  ...         0.12
Sleeping Dogs                                        4517  ...         0.43
Sleeping Dogs                                        7688  ...         0.20
Sleeping Dogs                                        1950  ...         1.06
Sleeping Dogs                                        2358  ...         0.88
Soul Eater: Monotone Princess                       15767  ...         0.02
The Legend of Kage 2                                11681  ...         0.08
The Tomb Raider Trilogy                              2197  ...         0.94
Thief (2014)                                         4311  ...         0.45
Thief (2014)                                         2454  ...         0.84
Thief (2014)                                        10226  ...         0.11
Thief (2014)                                         4802  ...         0.40
Thief (2014)                                         5955  ...         0.30
Tomb Raider (2013)                                    613  ...         2.51
Tomb Raider (2013)                                   1367  ...         1.41
Tomb Raider (2013)                                    895  ...         1.92
Tomb Raider (2013)                                   3361  ...         0.60

[51 rows x 10 columns]

In [49]:
# OR
sales[square_enix | action_genre]

                                    Rank Platform  ...  Other_Sales Global_Sales
Name                                               ...
.hack: Sekai no Mukou ni + Versus  14279      PS3  ...         0.00         0.03
007: Quantum of Solace              1275     X360  ...         0.14         1.49
007: Quantum of Solace              9320       DS  ...         0.01         0.14
007: Quantum of Solace              4501      PS2  ...         0.26         0.43
007: Quantum of Solace              3040      Wii  ...         0.07         0.67
...                                  ...      ...  ...          ...          ...
[Prototype]                         1505     X360  ...         0.12         1.31
[Prototype]                         1604      PS3  ...         0.19         1.24
inFAMOUS                             488      PS3  ...         0.37         2.94
inFAMOUS 2                           941      PS3  ...         0.23         1.85
inFAMOUS: Second Son                 539      PS4  ...         0.47         2.78

[3433 rows x 10 columns]

In [50]:
over_ten_million_sales = sales["Global_Sales"] > 10
sales[over_ten_million_sales]

                                              Rank  ... Global_Sales
Name                                                ...
Animal Crossing: Wild World                     42  ...        12.27
Brain Age 2: More Training in Minutes a Day     28  ...        15.30
Brain Age: Train Your Brain in Minutes a Day    20  ...        20.22
Call of Duty: Black Ops                         41  ...        12.73
Call of Duty: Black Ops                         32  ...        14.64
...                                            ...  ...          ...
Wii Fit                                         14  ...        22.72
Wii Fit Plus                                    15  ...        22.00
Wii Play                                         8  ...        29.02
Wii Sports                                       1  ...        82.74
Wii Sports Resort                                4  ...        33.00

[62 rows x 10 columns]

In [51]:
early_90s_games = sales["Year"].between(1991, 1995)
sales[early_90s_games]

                                                  Rank  ... Global_Sales
Name                                                    ...
3D Lemmings                                      12587  ...         0.06
A llI S.V.: A Ressha de Gyoukou 3 Super Version  12387  ...         0.06
A-Train                                          11531  ...         0.08
A. IV Evolution: A Ressha de Ikou 4               6643  ...         0.25
Agile Warrior F-111X                              9209  ...         0.14
...                                                ...  ...          ...
Zen-Nippon GT Senshuken                          13737  ...         0.04
Zero Divide                                      12725  ...         0.06
Zero4 Champ RR                                    5168  ...         0.36
Zero4 Champ RR-Z                                 10686  ...         0.10
Zoop                                             13272  ...         0.05

[484 rows x 10 columns]

In [52]:
# Aggregate Operations
# Mean
sales["Global_Sales"].mean()

0.540231518343868

In [53]:
sales["Global_Sales"].sum()

8820.36

In [54]:
sales["Global_Sales"].max()

82.74

In [55]:
sales["Global_Sales"].min()

0.01

In [56]:
genre_group = sales.groupby("Genre")

In [57]:
# calculates the sum of global sales per genre
genre_group["Global_Sales"].sum()

Genre
Action          1722.88
Adventure        234.80
Fighting         444.05
Misc             797.62
Platform         829.15
Puzzle           242.22
Racing           726.77
Role-Playing     923.84
Shooter         1026.20
Simulation       390.16
Sports          1309.24
Strategy         173.43
Name: Global_Sales, dtype: float64

In [58]:
genre_group["Global_Sales"].sum().sort_values(ascending = False)

Genre
Action          1722.88
Sports          1309.24
Shooter         1026.20
Role-Playing     923.84
Platform         829.15
Misc             797.62
Racing           726.77
Fighting         444.05
Simulation       390.16
Puzzle           242.22
Adventure        234.80
Strategy         173.43
Name: Global_Sales, dtype: float64

In [59]:
genre_group["Global_Sales"].sum().mean()

735.0299999999971

In [60]:
# Melting
## "unpivoting"
sales.head()

                                         Rank  ... Global_Sales
Name                                           ...
'98 Koshien                              4756  ...         0.41
.hack//G.U. Vol.1//Rebirth               8359  ...         0.17
.hack//G.U. Vol.2//Reminisce             7109  ...         0.23
.hack//G.U. Vol.2//Reminisce (jp sales)  8604  ...         0.16
.hack//G.U. Vol.3//Redemption            8306  ...         0.17

[5 rows x 10 columns]

In [61]:
sales.reset_index(inplace = True)

In [62]:
sales.head()

                                      Name  Rank  ... Other_Sales  Global_Sales
0                              '98 Koshien  4756  ...        0.03          0.41
1               .hack//G.U. Vol.1//Rebirth  8359  ...        0.00          0.17
2             .hack//G.U. Vol.2//Reminisce  7109  ...        0.03          0.23
3  .hack//G.U. Vol.2//Reminisce (jp sales)  8604  ...        0.00          0.16
4            .hack//G.U. Vol.3//Redemption  8306  ...        0.00          0.17

[5 rows x 11 columns]

In [63]:
## Wide and tall datasets

In [66]:
# Region Sales
# NA 0.11
# EU 0.3
# JP 0.2
sales.melt(
    id_vars = ["Name", "Publisher"],
    value_vars = ["NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales"],
    var_name = "Region",
    value_name = "Sales"
    )

                                          Name  ... Sales
0                                  '98 Koshien  ...  0.15
1                   .hack//G.U. Vol.1//Rebirth  ...  0.00
2                 .hack//G.U. Vol.2//Reminisce  ...  0.11
3      .hack//G.U. Vol.2//Reminisce (jp sales)  ...  0.00
4                .hack//G.U. Vol.3//Redemption  ...  0.00
...                                        ...  ...   ...
65303               thinkSMART: Chess for Kids  ...  0.00
65304                             uDraw Studio  ...  0.20
65305             uDraw Studio: Instant Artist  ...  0.02
65306             uDraw Studio: Instant Artist  ...  0.00
65307             Â¡Shin Chan Flipa en colores!  ...  0.00

[65308 rows x 4 columns]